### ISSUE TITLE
FlyingV stopped working.

### ISSUE THREAD

**Issue by ianpurton** [tomash/flyingv#1]
It seems to work ok for values that already exists. i.e. from your examples.

FlyingV.post("123somekey", "And this is some value, 64kb being its length limit")

Net::HTTPOK 200 OK readbody=true 

But for a value that doesn't yet exist, i.e. add a random number to the end of the key.

FlyingV.post("123somekey55", "And this is some value, 64kb being its
length limit")

Net::HTTPInternalServerError 500 Internal Server Error readbody=true

This seems to have started failing from around about the new year.

Any ideas ?

**Comment by tomash** [comment]
Whoa, I had no idea that OpenKeyVal still operates and that someone actually is using FlyingV.

Reproduced it. Weird, looks as if okv stopped working. Will try to launch local copy of the service to see what's wrong.
